package string;

import java.util.Arrays;

// 389. Find the Difference
// Easy

// 859

// 286

// Add to List

// Share
// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.
// Accepted
// 202,473
// Submissions
// 365,784


public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        char[] arrS = s.toCharArray();
        char[] arrT = t.toCharArray();
        Arrays.sort(arrS);
        Arrays.sort(arrT);
        for(int i = 0; i < arrS.length; i++) {
            if(arrS[i] != arrT[i]) return arrT[i];
        }    
        return arrT[arrT.length - 1];
    }
}